export const CHOICES = [
  { id: 'DATA_SCIENCE', title: 'Data science' },
  { id: 'PROGRAMMING', title: 'Programming' },
  { id: 'ARTIFICIAL_INTELLIGENCE', title: 'Artificial Intelligence' },
  { id: 'BUSINESS', title: 'Business' },
  { id: 'AUTONOMOUS_VEHICLES', title: 'Autonomous vehicles' },
  { id: 'CLOUD_COMPUTING', title: 'Cloud Computing' },
];

export const DATA_SCIENCE = [
  {
    class: 'data-science-1',
    state: 'new',
    title: 'Data Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '5 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-2',
    state: 'popular',
    title: 'Data Analyst',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-3',
    state: 'popular',
    title: 'Data Scientist',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-4',
    state: 'new',
    title: 'Data Product Manager',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '3 months at 10 hrs/week',
  },
  {
    class: 'data-science-5',
    state: 'top rated',
    title: 'Programming DS Python',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-6',
    state: 'popular',
    title: 'Business Analytics',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-7',
    state: 'new',
    title: 'SQL',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '2 months at 10 hrs/week',
  },
  {
    class: 'data-science-8',
    state: 'new',
    title: 'Data Structures & Algorithms',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '2 months at 10 hrs/week',
  },
];

export const PROGRAMMING = [
  {
    class: 'programming-1',
    state: 'new',
    title: 'Data Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '5 months at 5-10 hrs/week',
  },
  {
    class: 'programming-2',
    state: 'new',
    title: 'Full Stack Dev',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-3',
    state: 'popular',
    title: 'Intro to Programming',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-4',
    state: 'new',
    title: 'Front End Web Dev',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-5',
    state: 'popular',
    title: 'C++',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-6',
    state: 'new',
    title: 'Java Web Developer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-7',
    state: 'new',
    title: 'Data Structures & Algorithms',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-8',
    state: 'new',
    title: 'Cloud Developer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
];
