export const CHOICES = [
  { id: 'DATA_SCIENCE', title: 'Data science' },
  { id: 'PROGRAMMING', title: 'Programming' },
  { id: 'ARTIFICIAL_INTELLIGENCE', title: 'Artificial Intelligence' },
  { id: 'BUSINESS', title: 'Business' },
  { id: 'AUTONOMOUS_VEHICLES', title: 'Autonomous vehicles' },
  { id: 'CLOUD_COMPUTING', title: 'Cloud Computing' },
];

export const DATA_SCIENCE = [
  {
    class: 'data-science-1',
    state: 'new',
    title: 'Data Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '5 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-2',
    state: 'popular',
    title: 'Data Analyst',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-3',
    state: 'popular',
    title: 'Data Scientist',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-4',
    state: 'new',
    title: 'Data Product Manager',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '3 months at 10 hrs/week',
  },
  {
    class: 'data-science-5',
    state: 'top rated',
    title: 'Programming DS Python',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-6',
    state: 'popular',
    title: 'Business Analytics',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'data-science-7',
    state: 'new',
    title: 'SQL',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '2 months at 10 hrs/week',
  },
  {
    class: 'data-science-8',
    state: 'new',
    title: 'Data Structures & Algorithms',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '2 months at 10 hrs/week',
  },
];

export const PROGRAMMING = [
  {
    class: 'programming-1',
    state: 'new',
    title: 'Data Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '5 months at 5-10 hrs/week',
  },
  {
    class: 'programming-2',
    state: 'new',
    title: 'Full Stack Dev',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-3',
    state: 'popular',
    title: 'Intro to Programming',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-4',
    state: 'new',
    title: 'Front End Web Dev',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-5',
    state: 'popular',
    title: 'C++',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-6',
    state: 'new',
    title: 'Java Web Developer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-7',
    state: 'new',
    title: 'Data Structures & Algorithms',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'programming-8',
    state: 'new',
    title: 'Cloud Developer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
];

export const ARTIFICIAL_INTELLIGENCE = [
  {
    class: 'artificial-intelligence-1',
    state: 'popular',
    title: 'Deep Learning',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'artificial-intelligence-2',
    state: 'popular',
    title: 'Machine Learning Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'artificial-intelligence-3',
    state: 'popular',
    title: 'AI with Python',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'artificial-intelligence-4',
    state: 'popular',
    title: 'Data Structures % Algorithms',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'artificial-intelligence-5',
    state: 'new',
    title: 'Data Structures % Algorithms',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'artificial-intelligence-6',
    state: 'top-rated',
    title: 'AI for Trading',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '6 months at 5-10 hrs/week',
  },
];

export const BUSINESS = [
  {
    class: 'business-1',
    state: 'new',
    title: 'Product Manager',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'business-2',
    state: 'new',
    title: 'Data Product Manager',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'business-3',
    state: 'popular',
    title: 'Digital Marketing',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'business-4',
    state: 'popular',
    title: 'Business Analytics',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'business-5',
    state: 'new',
    title: 'UX Designer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Beginner',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'business-6',
    state: 'new',
    title: 'SQL',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
];

export const AUTONOMOUS_VEHICLES = [
  {
    class: 'autonomous-vehicles-1',
    state: 'popular',
    title: 'C++',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'autonomous-vehicles-2',
    state: 'popular',
    title: 'Self Driving Cars',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '6 months at 5-10 hrs/week',
  },
  {
    class: 'autonomous-vehicles-3',
    state: 'new',
    title: 'Robotics Software',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'autonomous-vehicles-4',
    state: 'top rated',
    title: 'Intro to Self Driving Cars',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'autonomous-vehicles-5',
    state: 'new',
    title: 'Robotics',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'autonomous-vehicles-6',
    state: 'top rated',
    title: 'Sensor Fusion Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
];

export const CLOUD_COMPUTING_CAROUSEL = [
  {
    class: 'cloud-computing-1',
    state: 'new',
    title: 'Cloud Developer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'cloud-computing-2',
    state: 'new',
    title: 'DevOps Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
  {
    class: 'cloud-computing-3',
    state: 'new',
    title: 'Cloud DevOps Engineer',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Intermediate',
    estimatedTime: '4 months at 5-10 hrs/week',
  },
  {
    class: 'cloud-computing-4',
    state: 'new',
    title: 'AWS Cloud Architect',
    stars: ['full', 'full', 'full', 'full', 'half'],
    difficulty: 'Advanced',
    estimatedTime: '3 months at 5-10 hrs/week',
  },
];
